name: VillagerWorkstationHighlights
main: com.github.joelgodofwar.vwh.VillagerWorkstationHighlights
version: 1.16_1.0.0
author: JoelYahwehOfWar
api-version: 1.13

commands:
  vwh:
    description: Shows Villager Workstation Highlight.
    usage: /<command>